"""init

Revision ID: af66457e3103
Revises: ded7b6794313
Create Date: 2026-04-10 00:09:17.600291

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'af66457e3103'
down_revision: Union[str, Sequence[str], None] = 'ded7b6794313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
