"""init

Revision ID: ded7b6794313
Revises: 
Create Date: 2026-04-09 18:12:28.341296

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'ded7b6794313'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
