"""init

Revision ID: f1804f151de5
Revises: af66457e3103
Create Date: 2026-04-10 13:31:37.961875

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'f1804f151de5'
down_revision: Union[str, Sequence[str], None] = 'af66457e3103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
