"""init

Revision ID: fea39bec74df
Revises:
Create Date: 2026-04-13 21:40:32.064787

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "fea39bec74df"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
