"""init

Revision ID: ffa242ba1baf
Revises: 92864e7978a4
Create Date: 2026-04-16 20:39:23.572567

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ffa242ba1baf"
down_revision: Union[str, Sequence[str], None] = "92864e7978a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("userId", sa.UUID(), nullable=False),
        sa.Column("login", sa.String(), nullable=False),
        sa.Column("passwordHash", sa.String(), nullable=False),
        sa.Column("firstName", sa.String(), nullable=True),
        sa.Column("lastName", sa.String(), nullable=True),
        sa.Column("patronymic", sa.String(), nullable=True),
        sa.Column("dateOfBirth", sa.Date(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("telegram", sa.String(), nullable=True),
        sa.Column("telegramChatId", sa.String(), nullable=True),
        sa.Column("isSeller", sa.Boolean(), nullable=True),
        sa.Column(
            "createdAt", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("userId"),
        sa.UniqueConstraint("login"),
    )
    op.create_index("idx_user_isSeller", "users", ["isSeller"], unique=False)
    op.create_table(
        "markets",
        sa.Column("marketId", sa.UUID(), nullable=False),
        sa.Column("userId", sa.UUID(), nullable=False),
        sa.Column("marketName", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "createdAt", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.userId"],
        ),
        sa.PrimaryKeyConstraint("marketId"),
    )
    op.create_index("idx_market_user", "markets", ["userId"], unique=False)
    op.create_table(
        "products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("marketId", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "electronics",
                "clothing",
                "food",
                "home",
                "beauty",
                "sports",
                "books",
                "other",
                name="productcategory",
            ),
            nullable=False,
        ),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("img", sa.String(), nullable=True),
        sa.Column("available", sa.Integer(), nullable=False),
        sa.Column(
            "createdAt", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.CheckConstraint("available >= 0", name="check_available_positive"),
        sa.ForeignKeyConstraint(
            ["marketId"],
            ["markets.marketId"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_product_category", "products", ["category"], unique=False)
    op.create_index("idx_product_market", "products", ["marketId"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_product_market", table_name="products")
    op.drop_index("idx_product_category", table_name="products")
    op.drop_table("products")
    op.drop_index("idx_market_user", table_name="markets")
    op.drop_table("markets")
    op.drop_index("idx_user_isSeller", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
